---
title: "Velocidade Média de Internet por Aluno nas Escolas Estaduais"
output: pdf_document
geometry: margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(kableExtra)
library(dplyr)

school_net_wrat <- readRDS("D:/Country/Brazil/TechBrazil/working/Bahia/school_net_wrat.rds")

# Create a summary by state (unique values of already grouped variable)
summary_state_speed <- school_net_wrat %>%
  select(NM_UF, state_weighted_actual) %>%
  distinct() %>%
  arrange(desc(state_weighted_actual)) %>%
  rename(
    `Unidade da Federação` = NM_UF,
    `Mbps por aluno (média ponderada)` = state_weighted_actual
  )

```


```{r, echo=FALSE}

summary_state_speed %>%
  kable("latex", booktabs = TRUE, align = "lr") %>%
  kable_styling(latex_options = c("striped", "hold_position"), full_width = FALSE) %>%
  row_spec(
    which(summary_state_speed$`Unidade da Federação` == "Bahia"), 
    bold = TRUE, 
    color = "red"
  )


```

\footnotetext{Fonte: Censo Escolar 2024 e SIMET (nic.br), 23/06/25}
