---
title: "Relatório de Cobertura CNCT–CBO"
author: ""
date: "`r format(Sys.Date(), '%d/%m/%Y')`"
output:
  pdf_document:
    number_sections: true
    toc: false
    latex_engine: pdflatex
    keep_tex: true
geometry: margin=1in
---

---

```{r setup, include=FALSE}
# Load required libraries
library(reticulate)
library(dplyr)
library(purrr)
library(tibble)
library(knitr)
library(writexl)

```

```{r echo=FALSE}
# Load the Python pickle file exported from df_summary
py <- import_builtins()
pd <- import("pandas")
df_summary <- pd$read_pickle("D:/Country/Brazil/TechBrazil/working/qbq/df_cnct_cbo_atual.pkl")

# Convert to R tibble
df_summary <- as_tibble(df_summary)
```

```{r echo=FALSE}
# Create column with unmatched CBOs
df_summary <- df_summary %>%
  mutate(
    unmatched_cbos = map2(cbo_list, matched_cbos, ~ setdiff(.x, .y)),
    num_unmatched = map_int(unmatched_cbos, length)
  )

# Filter only those with at least one unmatched CBO
df_unmatched <- df_summary %>%
  filter(num_unmatched > 0) %>%
  select(IDX_EIXCUR, Denominacao_Curso_CNCT, unmatched_cbos) %>%
  arrange(IDX_EIXCUR)

```

```{r echo=FALSE}
# Display table of unmatched CBOs
kable(df_unmatched, caption = "Cursos com CBOs Não Correspondidos")

```



```{r echo=FALSE, results='asis'}

filt <- df_summary %>% filter(num_unmatched > 0) %>%         
  arrange(IDX_EIXCUR) %>%  mutate(sec_title = paste(IDX_EIXCUR, Denominacao_Curso_CNCT, sep = " -- "))

# Loop through and emit LaTeX sections
for (i in seq_len(nrow(filt))) {
  curso <- filt[i, ]
  
  cat("\\newpage\n")
  cat("\\section{", curso$sec_title, "}\n\n")
  cat("**CBOs não correspondidos:** ", paste(unlist(curso$unmatched_cbos), collapse = ", "), "\n\n")
}

```
\footnotetext{Fonte: CNCT e QBQ, `r format(Sys.Date(), "%d/%m/%Y")`}




